#+TITLE: Vonpupp's Spacemacs configuration (user-config)
#+STARTUP: overview
#+STARTUP: indent

* Spacemacs configuration
** Org-protocol
*** Usage
Use the following extensions:
- Chrome: [[https://chrome.google.com/webstore/detail/org-capture/kkkjlfejijcjgjllecmnejhogpbcigdc]]
- Firefox: [[https://addons.mozilla.org/en-US/firefox/addon/org-capture/]]

Once installed an icon on the top of the browser should appear. To setup the
handler and the templates read: [[https://github.com/sprig/org-capture-extension]]

The '(server-start)' is needed under the 'user-init()' function on the init.el file.

*** Config
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  (require 'org-protocol)
#+END_SRC

** Org-babel
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  (org-babel-do-load-languages
   (quote org-babel-load-languages)
   (quote (
     (R . t)
     (calc . t)
     (ditaa . t)
     (dot . t)
     (emacs-lisp . t)
     (gnuplot . t)
     (gnuplot . t)
     (latex . t)
     (ledger . t)
     ;(ly . t)
     (matlab . t)
     (org . t)
     (plantuml . t)
     (python . t)
     (shell . t)
     (sql . t)
     (sqlite . t)
  )))
#+END_SRC

** Org-mode
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  ;; PATH AND IMPORTANT FILES
  (if (memq window-system '(w32))
      (setq my-home-dir "C:/Users/av")
    (setq my-home-dir (expand-file-name "~")))
  (setq org-directory (concat my-home-dir "/org/"))
  (setq org-default-capture-file (concat org-directory "capture.org"))

  ;; MODULES
  (setq org-modules (quote (org-habit)))
  (add-to-list 'org-modules 'org-protocol)

  ;; LOG
  (setq org-log-into-drawer "LOGBOOK")

  ;; AGENDA
  (setq org-agenda-files (directory-files-recursively org-directory "\\.org$"))
  ;; Doc: https://stackoverflow.com/a/29905161/1332764
  (setq org-agenda-include-diary t)
  (setq org-agenda-start-on-weekday 7)
  ;; (setq org-agenda-skip-function '(org-agenda-skip-entry-if 'todo '("HABIT" "REPEAT")))
  (setq org-agenda-custom-commands
   (quote (
     ;; gtd base states
     ("d" "TODO state" todo "TODO"
      ((org-agenda-overriding-header "TODO tasks")))
     ("s" "SOMEDAY state" todo "SOMEDAY"
      ((org-agenda-overriding-header "SOMEDAY tasks")))
     ("n" "NEXT state" todo "NEXT"
      ((org-agenda-overriding-header "NEXT tasks")))
     ("w" "WAITING state" todo "WAITING"
      ((org-agenda-overriding-header "WAITING tasks")))
     ("p" "PROJ state" todo "PROJ"
      ((org-agenda-overriding-header "PROJ tasks")))
     ("d" "DONE state" todo "DONE"
      ((org-agenda-overriding-header "DONE tasks")))
     ("c" "CANCELLED state" todo "CANCELLED"
      ((org-agenda-overriding-header "CANCELLED tasks")))
     ("k" "SKIPPED state" todo "SKIPPED"
      ((org-agenda-overriding-header "SKIPPED tasks")))
     ;; other filters
     ("l" "All actionable tasks" todo "TODO|NEXT|WAITING|PROJ"
      ((org-agenda-overriding-header "TODO tasks")))
     ("h" "Habits" tags-todo "+habit"
      ((org-agenda-overriding-header "Habits")))
     ("1" "ME" tags-todo "+ME"
      ((org-agenda-overriding-header "ME tag")))
     ("2" "RELATING" tags-todo "+RELATING"
      ((org-agenda-overriding-header "RELATING tag")))
     ("3" "DOING" tags-todo "+DOING"
      ((org-agenda-overriding-header "DOING tag")))
     ("i" "Important things to do"
      ((tags-todo "ME"
                  ((org-agenda-overriding-header "Me tag")))
       (tags-todo "RELATING"
                  ((org-agenda-overriding-header "Relating tag"))))
      nil nil)
  )))

  ;; REFILE
  (setq org-refile-targets (quote ((org-agenda-files :level . 1))))
  (setq org-refile-use-outline-path (quote full-file-path))
  (setq org-refile-allow-creating-parent-nodes (quote confirm))

  ;; ID
  (setq org-id-locations-file (concat org-directory ".org-id-locations"))

  ;; JOURNAL
  ;; https://github.com/syl20bnr/spacemacs/tree/develop/layers/%2Bemacs/org#org-journal-support
  (setq org-journal-dir (concat org-directory "journal/"))
  (setq org-journal-file-format "%Y-%m-%d")
  (setq org-journal-date-prefix "* ")
  ;;(setq org-journal-date-format "%A, %B %d %Y")
  (setq org-journal-date-format "%Y-%m-%d")
  (setq org-journal-time-prefix "* ")
  (setq org-journal-time-format "%Y-%m-%d %H:%M")
  (setq org-journal-time-format "%H:%M")

  ;; STATES
  ;; TIP: ~M-x org-mode-restart~ refreshes the org-mode cache
  (setq org-todo-keywords '((type "TODO(t/!)" "SOMEDAY(s/!)" "NEXT(n/!)" "WAITING(w@/!)" "PROJ(p)" "REPEAT(r/!)" "MEETING(m/!)" "|" "DONE(d)" "CANCELLED(c@/!)" "SKIPPED(k@/!)")))
  ;; (setq org-todo-keywords '(
  ;;   (sequence "TODO(t/!)" "NEXT(n/!)" "|" "DONE(d/!)")
  ;;   (sequence "HABIT(x)" "WAITING(w@/!)" "HOLD(h@/!)" "|" "CANCELLED(c@/!)" "PHONE" "MEETING")
  ;; ))

  ;; TAGS
  (setq org-tag-persistent-alist (quote (
    ("@home" . ?h)
    ("@work" . ?w)
    ("@phone" . ?p)
    ("@notebook" . ?n)
    ("@desktop" . ?d)
    ("review" . ?r)
    (:startgrouptag)
    ("me" . ?1)
    (:grouptags)
    ("spirit" . ?s)
    ("emotions" . ?e)
    ("mind" . ?m)
    ("body" . ?b)
    (:endgrouptag)
    (:startgrouptag)
    ("relating" . ?2)
    (:grouptags)
    ("partner" . ?l)
    ("parents" . ?o)
    ("extfamily" . ?x)
    ("neighbor" . ?g)
    ;; ("friends" . ?f)
    (:endgrouptag)
    (:startgrouptag)
    ("doing" . ?3)
    (:grouptags)
    ("finances" . ?f)
    ("stayinmalaga" . ?y)
    ("living" . ?v)
    (:endgrouptag)
  )))

  ;; FACES
  (setq org-todo-keyword-faces
        '(("TODO" . (:foreground "DarkOrange1" :weight bold))
          ("SOMEDAY" . (:foreground "sea green"))
          ("DONE" . (:foreground "light sea green"))
          ("CANCELLED" . (:foreground "forest green"))
          ("WAITING" . (:foreground "blue"))
         ))
  (setq org-tag-faces
        '(("ME" . (:foreground "forest green" :weight bold))
          ("SPIRIT" . (:foreground "lime green"))
          ("MIND" . (:foreground "forest green"))
          ("BODY" . (:foreground "yellow"))
         ))

  ;; Doc: https://github.com/sprig/org-capture-extension
  ;; (defun transform-square-brackets-to-round-ones(string-to-transform)
  ;;   "Transforms [ into ( and ] into ), other chars left unchanged."
  ;;   (concat
  ;;    (mapcar #'(lambda (c) (if (equal c ?[) ?\( (if (equal c ?]) ?\) c))) string-to-transform))
  ;;   )

  ;; CAPTURE
  (setq org-capture-templates
    '(
      ;; Doc: https://github.com/sprig/org-capture-extension
      ;; Doc: https://gist.github.com/cjp/64ac13f5966456841c197f70c7d3a53a
      ("p" "Protocol" entry (file+headline "~/org/capture.org" "Inbox")
       "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")
      ("L" "Protocol Link" entry (file+headline "~/org/capture.org" "Inbox")
       "* %? [[%:link][%:description]] \nCaptured On: %U")

      ;; ;; Doc: https://github.com/sprig/org-capture-extension
      ;; ("p" "Protocol" entry (file+headline ,(concat org-directory "capture.org") "Inbox")
      ;;  "* %^{Title}\nSource: %u, %c\n #+BEGIN_QUOTE\n%i\n#+END_QUOTE\n\n\n%?")
      ;; ("L" "Protocol Link" entry (file+headline ,(concat org-directory "capture.org") "Inbox")
      ;;  "* %? [[%:link][%(transform-square-brackets-to-round-ones \"%:description\")]]\n")

      ;; Templates for the TASKS keyword sequence
      ("t" "Tasks")

      ;; TEMPLATE A
      ("th" "SMART Habit" entry (file org-default-capture-file)
       "* REPEAT %^{Describe the task}       :HABIT:
  %?
  SCHEDULED: %(format-time-string \"%<<%Y-%m-%d %a .+1d>>\")
  :STYLE:    habit
  :SMART:
  :Specific:   %^{What is the purpose of this goal}
  :Measurable: %^{How can you measure it}
  :Activity:   %^{What activity do we need to do}
  :Resources:  %^{What resources do we need}
  :Timebox:    %^{What time do we need to spend on that}
  :Reviewed:
  :LOGBOOK:
  - Recorded: %U
  :HoursWeek:  Get it automatically
  :END:" :empty-lines 1)
  ))

  ;; EXPORT
  (setq org-export-backends
   (quote
    (beamer html icalendar latex man odt freemind taskjuggler)))

  ;; ----------------------------------------------------------------
  ;; Org Misc
  ;; ----------------------------------------------------------------
  ;; When hitting alt-return on a header, please create a new one without
  ;; messing up the one I'm standing on.
  (setq org-insert-heading-respect-content t)
  ;; Keep the indentation well structured by. OMG this is a must have. Makes
  ;; it feel less like editing a big text file and more like a purpose built
  ;; editor for org mode that forces the indentation.
  ;; (setq org-startup-indented t)
  ;; Open notes on a separate frame
  (setq org-noter-notes-window-location (quote (quote other-frame)))
  ;; This should allow to continue on last page but it is not working.
  ;; Needs review
  (setq org-noter-auto-save-last-location t)
#+END_SRC

** Spell check
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  (setq spell-checking-enable-auto-dictionary t)
  (setq enable-flyspell-auto-completion t)
#+END_SRC

** Pinentry
Doc: https://emacs.stackexchange.com/a/32882
Doc: https://github.com/syl20bnr/spacemacs-elpa-mirror/blob/master/gnu/pinentry-readme.txt

#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  (pinentry-start)
#+END_SRC

** Calendar
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  ;;(setq holiday-christian-holidays nil)
  ;;(setq holiday-hebrew-holidays t)
  ;;(setq holiday-islamic-holidays nil)
  ;;(setq holiday-bahai-holidays nil)
  ;;(setq holiday-oriental-holidays nil)

  ; Doc: https://www.emacswiki.org/emacs/CalendarWeekNumbers
  (copy-face 'default 'calendar-iso-week-header-face)
  (set-face-attribute 'calendar-iso-week-header-face nil
                      :height 1.0 :foreground "salmon")
  (setq calendar-intermonth-header
        (propertize "W"
                    'font-lock-face 'calendar-iso-week-header-face))

  (copy-face font-lock-constant-face 'calendar-iso-week-face)
  (set-face-attribute 'calendar-iso-week-face nil
                      :height 1.0 :foreground "salmon")
  (setq calendar-intermonth-text
        '(propertize
          (format "%2d"
                  (car
                   (calendar-iso-from-absolute
                    (calendar-absolute-from-gregorian (list month day year)))))
          'font-lock-face 'calendar-iso-week-face))

#+END_SRC

** Python
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  (setq python-shell-interpreter "ipython"
      python-shell-interpreter-args "--simple-prompt -i")
#+END_SRC

** Plantuml
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  (setq org-plantuml-jar-path
    (expand-file-name "/opt/plantuml/plantuml.jar"))
#+END_SRC

** Auto documentation with helm-descbinds-mode
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  ;; (require 'helm-descbinds)
  ;; (helm-descbinds-mode)
#+END_SRC

** Misc
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  ;; Do not ask for confirmation on some file configs
  (put 'org-todo-keyword-faces 'safe-local-variable #'listp)
  (add-to-list 'safe-local-variable-values
               '(eval flyspell-buffer))

  ;; Do not ask for confirmation to evaluate babel blocks
  (setq org-confirm-babel-evaluate nil)

  ;; Familiar zooming with Ctrl+ and Ctrl-
  (define-key global-map (kbd "C-=") 'text-scale-increase)
  (define-key global-map (kbd "C--") 'text-scale-decrease)

  ;; Flyspell commit messages
  (add-hook 'git-commit-setup-hook 'git-commit-turn-on-flyspell)

  (add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
#+END_SRC

** Org-impress                                                  :thirdparty:
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  (add-to-list 'load-path "~/.spacemacs.d/thirdparty/org-impress-js.el")
  (require 'ox-impress-js)
#+END_SRC

** Org-reveal                                                   :thirdparty:
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  ;;(add-to-list 'load-path "~/.spacemacs.d/thirdparty/org-reveal")
  ;;(require 'ox-reveal)
#+END_SRC

** Org-re-reveal                                                :thirdparty:
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  (add-to-list 'load-path "~/.spacemacs.d/thirdparty/org-re-reveal")
  (require 'org-re-reveal)
#+END_SRC

** Outshine (Org-mode bullets in Beancount)                     :thirdparty:
Doc: https://github.com/syl20bnr/spacemacs/issues/5258

#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  ; Source: https://www.reddit.com/r/emacs/comments/aay01i/announce_outshine_30_has_been_released/
  (require 'outshine)
  (add-hook 'beancount-mode-hook 'outshine-mode)
#+END_SRC
** PDF Tools (org-noter)                                        :thirdparty:
#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  (add-to-list 'load-path "~/.spacemacs.d/thirdparty/pdf-tools-org")
  (require 'pdf-tools-org)
#+END_SRC

** Edit server                                                  :thirdparty:
Doc: https://www.emacswiki.org/emacs/Edit_with_Emacs

#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  ;; ----------------------------------------------------------------
  ;; Third party modules
  ;; ----------------------------------------------------------------

  (add-to-list 'load-path "~/.spacemacs.d/thirdparty/editserver")
  (require 'edit-server)
  (edit-server-start)
#+END_SRC

** Openwith                                                     :thirdparty:
Doc: https://stackoverflow.com/questions/51006855/open-mp4-files-from-orgmode

#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  (require 'openwith)
  (openwith-mode t)
  (setq openwith-associations '(("\\.mp4\\'" "mpv" (file))))
#+END_SRC

** DTK                                                          :thirdparty:
Doc: https://github.com/dtk01/dtk

#+BEGIN_SRC emacs-lisp :tangle ~/.spacemacs.d/config-public/public-config.el
  ;;(add-to-list 'load-path "~/.spacemacs.d/thirdparty/diatheke.el")
  ;;(require 'diatheke)
  (add-to-list 'load-path "~/.spacemacs.d/thirdparty/dtk")
  (require 'dtk)

  (use-package dtk
    :bind (("C-c B" . dtk-bible))
    :custom
    (dtk-default-module "nvi")
    (dtk-default-module-category "Biblical Texts")
    (dtk-word-wrap t)
    )
#+END_SRC

** Novel

* Tasks [0%] [0/3]                                                 :noexport:
** TODO ox-json
- https://www.reddit.com/r/emacs/comments/ccwl4r/i_made_a_json_export_back_end_for_org_mode/
** TODO ob-translate
- https://github.com/krisajenkins/ob-translate
** TODO ob-browser
- https://github.com/krisajenkins/ob-browser
** FIX edit-server
* Build                                                            :noexport:
